-- MySQL Script generated by MySQL Workbench
-- Tue Sep 18 15:51:03 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema FID
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `FID` ;

-- -----------------------------------------------------
-- Schema FID
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `FID` DEFAULT CHARACTER SET utf8 ;
USE `FID` ;

-- -----------------------------------------------------
-- Table `FID`.`usuario_tipos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `FID`.`usuario_tipos` ;

CREATE TABLE IF NOT EXISTS `FID`.`usuario_tipos` (
  `usuario_tipo_id` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`usuario_tipo_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FID`.`Usuarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `FID`.`Usuarios` ;

CREATE TABLE IF NOT EXISTS `FID`.`Usuarios` (
  `usuario_id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `apellido` VARCHAR(45) NULL,
  `email` VARCHAR(100) NOT NULL,
  `password` VARCHAR(200) NOT NULL,
  `telefono` VARCHAR(50) NULL,
  `direccion` VARCHAR(200) NULL,
  `imagen` VARCHAR(200) NULL,
  `usuario_tipo_id` INT NOT NULL,
  PRIMARY KEY (`usuario_id`, `usuario_tipo_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FID`.`categorias`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `FID`.`categorias` ;

CREATE TABLE IF NOT EXISTS `FID`.`categorias` (
  `categoria_id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`categoria_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FID`.`Productos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `FID`.`Productos` ;

CREATE TABLE IF NOT EXISTS `FID`.`Productos` (
  `producto_id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `codigo` VARCHAR(45) NOT NULL,
  `tipo_producto` VARCHAR(45) NOT NULL,
  `talla` VARCHAR(45) NULL,
  `color` VARCHAR(45) NULL,
  `es_destacado` TINYINT NULL,
  `precio` FLOAT NOT NULL,
  `precio_lista` FLOAT NULL,
  `cantidad` DOUBLE NULL,
  `descripcion` VARCHAR(200) NULL,
  `categoria_id` INT NOT NULL,
  `imagen` VARCHAR(200) NULL,
  PRIMARY KEY (`producto_id`, `categoria_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FID`.`compras`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `FID`.`compras` ;

CREATE TABLE IF NOT EXISTS `FID`.`compras` (
  `compra_id` INT NOT NULL AUTO_INCREMENT,
  `importe_total` FLOAT NULL,
  `fecha_de_compra` DATETIME NOT NULL,
  `Usuarios_usuario_id` INT NOT NULL,
  PRIMARY KEY (`compra_id`))
ENGINE = InnoDB
COMMENT = '		';


-- -----------------------------------------------------
-- Table `FID`.`compras_detalle`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `FID`.`compras_detalle` ;

CREATE TABLE IF NOT EXISTS `FID`.`compras_detalle` (
  `compra_detalle_id` INT NOT NULL AUTO_INCREMENT,
  `cantidad` DOUBLE NOT NULL,
  `talla` VARCHAR(45) NULL,
  `codigo_producto` VARCHAR(45) NULL,
  `color` VARCHAR(45) NULL,
  `precio` FLOAT NOT NULL,
  `comentarios` VARCHAR(100) NULL,
  `compra_id` INT NOT NULL,
  `producto_id` INT NOT NULL,
  PRIMARY KEY (`compra_detalle_id`, `compra_id`, `producto_id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
