-- MySQL Script generated by MySQL Workbench
-- Fri Sep 21 21:33:44 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema FID
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `FID` ;

-- -----------------------------------------------------
-- Schema FID
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `FID` DEFAULT CHARACTER SET utf8 ;
USE `FID` ;

-- -----------------------------------------------------
-- Table `FID`.`users_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `FID`.`users_type` ;

CREATE TABLE IF NOT EXISTS `FID`.`users_type` (
  `user_type_id` INT NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`user_type_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FID`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `FID`.`users` ;

CREATE TABLE IF NOT EXISTS `FID`.`users` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `last_name` VARCHAR(45) NULL,
  `email` VARCHAR(100) NOT NULL,
  `password` VARCHAR(200) NOT NULL,
  `telephone` VARCHAR(50) NULL,
  `address` VARCHAR(200) NULL,
  `image` VARCHAR(200) NULL,
  `user_type_id` INT NOT NULL,
  PRIMARY KEY (`user_id`, `user_type_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FID`.`category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `FID`.`category` ;

CREATE TABLE IF NOT EXISTS `FID`.`category` (
  `category_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`category_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FID`.`subcategorys`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `FID`.`subcategorys` ;

CREATE TABLE IF NOT EXISTS `FID`.`subcategorys` (
  `sub_category_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `category_category_id` INT NOT NULL,
  PRIMARY KEY (`sub_category_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FID`.`products`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `FID`.`products` ;

CREATE TABLE IF NOT EXISTS `FID`.`products` (
  `product_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `product_code` VARCHAR(45) NOT NULL,
  `product_type` VARCHAR(45) NOT NULL,
  `size` VARCHAR(45) NULL,
  `color` VARCHAR(45) NULL,
  `is_popular` TINYINT NULL,
  `price` FLOAT NOT NULL,
  `price_list` FLOAT NULL,
  `quantity` DOUBLE NULL,
  `description` VARCHAR(200) NULL,
  `category_id` INT NOT NULL,
  `image` VARCHAR(200) NULL,
  `subcategorys_sub_category_id` INT NULL,
  PRIMARY KEY (`product_id`, `category_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FID`.`purcharse_orders`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `FID`.`purcharse_orders` ;

CREATE TABLE IF NOT EXISTS `FID`.`purcharse_orders` (
  `purcharse_order_id` INT NOT NULL AUTO_INCREMENT,
  `total` FLOAT NULL,
  `purcharse_order_date` DATETIME NOT NULL,
  `usuario_user_id` INT NOT NULL,
  PRIMARY KEY (`purcharse_order_id`))
ENGINE = InnoDB
COMMENT = '		';


-- -----------------------------------------------------
-- Table `FID`.`purcharse_order_details`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `FID`.`purcharse_order_details` ;

CREATE TABLE IF NOT EXISTS `FID`.`purcharse_order_details` (
  `compra_detalle_id` INT NOT NULL AUTO_INCREMENT,
  `quantity` DOUBLE NOT NULL,
  `price` FLOAT NOT NULL,
  `purcharse_order_id` INT NOT NULL,
  `product_id` INT NOT NULL,
  PRIMARY KEY (`compra_detalle_id`, `purcharse_order_id`, `product_id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
